language: go

dist: trusty
sudo: false

go:
    - 1.x
    - tip

install: 
    - go get gopkg.in/alecthomas/kingpin.v2

#before_install:
#    - echo "deb http://ftp.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/90-jessie-backports.list
#    - sudo apt -qq update
#    - sudo apt upgrade 

addons:
  apt:
    packages:
        - ragel

script: 
    - ragel --version
    - make test

matrix:
  allow_failures:
      - go: tip
