language: go

go:
- "1.9"
- "1.10"
- tip

addons:
  apt:
    packages:
    - ragel

env:
  global:
    secure: "Gyz5ao/rfC37rkJkNpMCqLUwL8OtuLpYY64qxyEDKJEw6phjK4fJBImqt4fdsKvzGUPgmww5WbReS84voFBc+ckod4sXT3WiD4T7TN0qAU6ntBjb42TO0O7VwG7kRkfnrdtuseT+DxTVhvIxREcUTlHwJHnUbFBh0fWbNeSPBScAnK017OGm6xY9GEt/1gMZu4QYM964zhKRJVSZ0+2UDKiVg4WNKRfOT9F1GkxqEhojUataNcrxWCpM0dXWrMk6lZS2YMKgLwSAbvbMnwxPe+FG2ZxVFUlfZYeksutpQPzJh5qYHXRFyk3EkzSV4+gSfac/1qwpQCxWQSk7znHZK6FtnYJi/Em2YWlfkW/8kqBwdRhEx6ZXkxMl3YFeaVg0pCAt1RhOll8YzzKvGztSDUS9LdCZMaGnh++gRb10xIAv0hz3cX/taU8mUMQ3EWTsSkTFPvgLRzVIEuHtxABLcg2OqpKvmFSLRDpJWxeS1InVpbhppXaZDtj2JyFiq4pmybMxvhVyda5jI4baqseq701/t5pLeSi/qIQGS7wWuYmMa3T/woRcDhq328WFKQco4mgRi9Rpf17THOp3HYvbwn9YZ78ML+9MGTcW52QBCtPzjAaU275dp7W6U2+fj5pbMfSkz4jv9E9oGaaw76Vc6b15An9PFOyLk0Z1JoYAS/c="

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get github.com/modocache/gover

script:
- export GOPATH="$GOPATH:$(pwd)"
- ragel --version
- make test

after_success:
- export GOPATH="$GOPATH:$(pwd)"
- go test -cover -coverprofile markdown.coverprofile markdown
- go test -cover -coverprofile parser.coverprofile parser
- gover
- wc -l gover.coverprofile
- bash <(curl -s https://codecov.io/bash) -f gover.coverprofile
