language: go

go:
- "1.9"
- "1.10"
- tip

addons:
  apt:
    packages:
    - ragel

env:
  global:
    secure: L65qZXwumQngpbZUUvpz9knNDzS53l/mvyaIYv6/BA9y7jsb87PVsL0gELCzjNKuS2pobzs5hMbpSMmFty4ApJ33R4+UlHRPZkpR+5iJKam3jcBUkegfZu/cPxMxAJnuUwQCoOOKDC+y5zVh4ubUlE3nin1qZA8AgJeDYWS0cALSK8EXb6cLN98x9GVXH2GbNQj2GeFDOjD3NGpSu19RokDdpW6JJ9MBWIwmbTh7SlcHl/wYro0w1GzGl6MQxXx/n3+c7U4E5+Qm2dapOUwncORBnAAAPEKtO+amkmaYQl3Tzc2uMtXrMs8Z11t2/NzuN2BTGPenG72+8i6RRCeosAq9Qu14k9TuBwUoth3MNTNwA9jpNUHjnTsnArk0w113eIncI+h11++WksDlE8rz71IbiPY7eNehlK3+Mo5nWaRCKzi7GbM0ScZ+L9o1cBuS3yd+hQdlkGUZGH+xSoFaZLg6blUfCMy5Y+46ZOEmdJrVZ3PW5UmOh1Pm6rixwgZiGYAPS0nD0Ss2n7WSsp2xe/0/bPLJzyBE0NJJION/EZcLhruxkPLs3Jli4u/JAuh/I5JJfyFCl0UTTF4MpyAp5iO8G2Trf7koguhVRfAhcZ3bKMKKab2IjdcOTN3CO+zo1K0ABsGU29jmgrCXWPts96Ex3nBPDGZvv59Q9na3kl0=
matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get github.com/mattn/goveralls
- go get github.com/dave/courtney

script:
- export GOPATH="$GOPATH:$(pwd)"
- ragel --version
- make test

after_success:
- export GOPATH="$GOPATH:$(pwd)"
- courtney -o coverage_markdown.out markdown
- courtney -o coverage_parser.out parser
- goveralls -coverprofile=coverage_markdown.out -service=travis-ci -repotoken $COVERALLS_TOKEN
- goveralls -coverprofile=coverage_parser.out -service=travis-ci -repotoken $COVERALLS_TOKEN
